apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brewery-ingress
  namespace: brewery
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: brewery.rsscloud.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: brewery
                port:
                  number: 8080
  ingressClassName: nginx

