apiVersion: v2
name: brewery
description: A Helm chart for Kubernetes to deploy a brewery application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Reinaldo Solano
    email: reinaldo.solano@gmail.com
sources:
  - https://github.com/ReinaldoSolano/brewery